from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(558, 451)
        Login.setStyleSheet("background: #302e2d")
        self.gridLayout_2 = QtWidgets.QGridLayout(Login)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 1, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.login_ed = QtWidgets.QLineEdit(Login)
        self.login_ed.setMinimumSize(QtCore.QSize(270, 30))
        self.login_ed.setMaximumSize(QtCore.QSize(270, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.login_ed.setFont(font)
        self.login_ed.setStyleSheet("background: #2B2B2B; color: #F68B00; border: #2B2B2B")
        self.login_ed.setText("")
        self.login_ed.setObjectName("login_ed")
        self.gridLayout.addWidget(self.login_ed, 3, 2, 1, 1)
        self.password_ed = QtWidgets.QLineEdit(Login)
        self.password_ed.setMinimumSize(QtCore.QSize(270, 30))
        self.password_ed.setMaximumSize(QtCore.QSize(270, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.password_ed.setFont(font)
        self.password_ed.setStyleSheet("background: #2B2B2B; color: #F68B00; border: #2B2B2B")
        self.password_ed.setText("")
        self.password_ed.setObjectName("password_ed")
        self.gridLayout.addWidget(self.password_ed, 5, 2, 1, 1)
        self.log_lab = QtWidgets.QLabel(Login)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.log_lab.setFont(font)
        self.log_lab.setStyleSheet("color: #e89517")
        self.log_lab.setObjectName("log_lab")
        self.gridLayout.addWidget(self.log_lab, 2, 2, 1, 1)
        self.new_account_check = QtWidgets.QCheckBox(Login)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(232, 149, 23))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(48, 46, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 149, 23))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 149, 23))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(48, 46, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(48, 46, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 149, 23))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(48, 46, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 149, 23))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 149, 23))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(48, 46, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(48, 46, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 149, 23))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(48, 46, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 149, 23))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 149, 23))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(48, 46, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(48, 46, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.new_account_check.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.new_account_check.setFont(font)
        self.new_account_check.setStyleSheet("color: #e89517")
        self.new_account_check.setObjectName("new_account_check")
        self.gridLayout.addWidget(self.new_account_check, 3, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(Login)
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 6, 2, 1, 1)
        self.dialog_lab = QtWidgets.QLabel(Login)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.dialog_lab.setFont(font)
        self.dialog_lab.setStyleSheet("color: rgb(255, 0, 0)")
        self.dialog_lab.setText("")
        self.dialog_lab.setObjectName("dialog_lab")
        self.gridLayout.addWidget(self.dialog_lab, 7, 1, 1, 1)
        self.bromnitsa_lab = QtWidgets.QLabel(Login)
        self.bromnitsa_lab.setMinimumSize(QtCore.QSize(270, 160))
        self.bromnitsa_lab.setMaximumSize(QtCore.QSize(270, 160))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.bromnitsa_lab.setFont(font)
        self.bromnitsa_lab.setStyleSheet("color: #e58020")
        self.bromnitsa_lab.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.bromnitsa_lab.setObjectName("bromnitsa_lab")
        self.gridLayout.addWidget(self.bromnitsa_lab, 1, 2, 1, 1)
        self.login_but = QtWidgets.QPushButton(Login)
        self.login_but.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.login_but.setFont(font)
        self.login_but.setStyleSheet("background: #3C3C3B; color: #e59720")
        self.login_but.setObjectName("login_but")
        self.gridLayout.addWidget(self.login_but, 7, 2, 1, 1)
        self.gallery_lab = QtWidgets.QLabel(Login)
        self.gallery_lab.setMinimumSize(QtCore.QSize(270, 80))
        self.gallery_lab.setMaximumSize(QtCore.QSize(270, 80))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.gallery_lab.setFont(font)
        self.gallery_lab.setStyleSheet("color: #e89517")
        self.gallery_lab.setObjectName("gallery_lab")
        self.gridLayout.addWidget(self.gallery_lab, 0, 2, 1, 1)
        self.password_lab = QtWidgets.QLabel(Login)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.password_lab.setFont(font)
        self.password_lab.setStyleSheet("color: #e89517")
        self.password_lab.setObjectName("password_lab")
        self.gridLayout.addWidget(self.password_lab, 4, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 8, 2, 1, 1)
        self.frame = QtWidgets.QFrame(Login)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(Login)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout.addWidget(self.frame_2, 1, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(Login)
        self.frame_3.setMinimumSize(QtCore.QSize(250, 250))
        self.frame_3.setMaximumSize(QtCore.QSize(250, 250))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.icon_lab = QtWidgets.QLabel(self.frame_3)
        self.icon_lab.setGeometry(QtCore.QRect(20, 20, 170, 170))
        self.icon_lab.setMinimumSize(QtCore.QSize(170, 170))
        self.icon_lab.setObjectName("icon_lab")
        self.gridLayout.addWidget(self.frame_3, 0, 1, 2, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Войти в галерею"))
        self.log_lab.setText(_translate("Login", "Логин:"))
        self.new_account_check.setText(_translate("Login", "Новый аккаунт"))
        self.bromnitsa_lab.setText(_translate("Login", "\"Бромница\""))
        self.login_but.setText(_translate("Login", "Войти"))
        self.gallery_lab.setText(_translate("Login", "Галерея"))
        self.password_lab.setText(_translate("Login",
                                             "Пароль: (Не менее 6 символов)"))
        self.icon_lab.setText(_translate("Login", "TextLabel"))


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(833, 660)
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        MainWindow.setIconSize(QtCore.QSize(70, 70))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.photo_lab = QtWidgets.QLabel(self.centralwidget)
        self.photo_lab.setMinimumSize(QtCore.QSize(200, 200))
        self.photo_lab.setMaximumSize(QtCore.QSize(200, 200))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.photo_lab.setFont(font)
        self.photo_lab.setAlignment(QtCore.Qt.AlignCenter)
        self.photo_lab.setObjectName("photo_lab")
        self.verticalLayout.addWidget(self.photo_lab)
        self.add_album_but = QtWidgets.QPushButton(self.centralwidget)
        self.add_album_but.setMinimumSize(QtCore.QSize(0, 40))
        self.add_album_but.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.add_album_but.setFont(font)
        self.add_album_but.setObjectName("add_album_but")
        self.verticalLayout.addWidget(self.add_album_but)
        self.settings_but = QtWidgets.QPushButton(self.centralwidget)
        self.settings_but.setMinimumSize(QtCore.QSize(0, 40))
        self.settings_but.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.settings_but.setFont(font)
        self.settings_but.setObjectName("settings_but")
        self.verticalLayout.addWidget(self.settings_but)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.nik_lab = QtWidgets.QLabel(self.centralwidget)
        self.nik_lab.setMinimumSize(QtCore.QSize(80, 0))
        self.nik_lab.setMaximumSize(QtCore.QSize(300, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.nik_lab.setFont(font)
        self.nik_lab.setAlignment(QtCore.Qt.AlignCenter)
        self.nik_lab.setWordWrap(True)
        self.nik_lab.setObjectName("nik_lab")
        self.gridLayout.addWidget(self.nik_lab, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(38, 48, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.search_ed = QtWidgets.QLineEdit(self.centralwidget)
        self.search_ed.setMinimumSize(QtCore.QSize(225, 30))
        self.search_ed.setMaximumSize(QtCore.QSize(300, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.search_ed.setFont(font)
        self.search_ed.setObjectName("search_ed")
        self.horizontalLayout.addWidget(self.search_ed)
        self.search_but = QtWidgets.QPushButton(self.centralwidget)
        self.search_but.setMinimumSize(QtCore.QSize(80, 25))
        self.search_but.setObjectName("search_but")
        self.horizontalLayout.addWidget(self.search_but)
        spacerItem2 = QtWidgets.QSpacerItem(48, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 2, 1, 1)
        self.alb_grid = QtWidgets.QGridLayout()
        self.alb_grid.setObjectName("alb_grid")
        self.gridLayout.addLayout(self.alb_grid, 1, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 2, 1, 1)
        self.scroll = QtWidgets.QScrollBar(self.centralwidget)
        self.scroll.setStyleSheet("")
        self.scroll.setMinimum(0)
        self.scroll.setMaximum(0)
        self.scroll.setOrientation(QtCore.Qt.Vertical)
        self.scroll.setObjectName("scroll")
        self.gridLayout_2.addWidget(self.scroll, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 833, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Галерея \"Бромница\""))
        self.photo_lab.setText(_translate("MainWindow", "Фото"))
        self.add_album_but.setText(_translate("MainWindow", "Добавить альбом"))
        self.settings_but.setText(_translate("MainWindow", "Настройки ⚙"))
        self.nik_lab.setText(_translate("MainWindow", "Ник"))
        self.search_ed.setText(_translate("MainWindow", "Поиск"))
        self.search_but.setText(_translate("MainWindow", "Поиск 🔍 "))


class Ui_AlbumsSettings(object):
    def setupUi(self, AlbumsSettings):
        AlbumsSettings.setObjectName("AlbumsSettings")
        AlbumsSettings.resize(600, 300)
        AlbumsSettings.setMinimumSize(QtCore.QSize(600, 300))
        AlbumsSettings.setMaximumSize(QtCore.QSize(800, 500))
        self.gridLayout_3 = QtWidgets.QGridLayout(AlbumsSettings)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.title_lab = QtWidgets.QLabel(AlbumsSettings)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.title_lab.setFont(font)
        self.title_lab.setObjectName("title_lab")
        self.gridLayout_2.addWidget(self.title_lab, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 3, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.to_themes_but = QtWidgets.QPushButton(AlbumsSettings)
        self.to_themes_but.setMinimumSize(QtCore.QSize(0, 40))
        self.to_themes_but.setMaximumSize(QtCore.QSize(200, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.to_themes_but.setFont(font)
        self.to_themes_but.setObjectName("to_themes_but")
        self.gridLayout.addWidget(self.to_themes_but, 1, 0, 1, 1)
        self.to_alb_view_but = QtWidgets.QPushButton(AlbumsSettings)
        self.to_alb_view_but.setMinimumSize(QtCore.QSize(0, 40))
        self.to_alb_view_but.setMaximumSize(QtCore.QSize(200, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.to_alb_view_but.setFont(font)
        self.to_alb_view_but.setObjectName("to_alb_view_but")
        self.gridLayout.addWidget(self.to_alb_view_but, 1, 1, 1, 1)
        self.to_user_but = QtWidgets.QPushButton(AlbumsSettings)
        self.to_user_but.setMinimumSize(QtCore.QSize(0, 40))
        self.to_user_but.setMaximumSize(QtCore.QSize(200, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.to_user_but.setFont(font)
        self.to_user_but.setObjectName("to_user_but")
        self.gridLayout.addWidget(self.to_user_but, 1, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 1)
        self.fone = QtWidgets.QFrame(AlbumsSettings)
        self.fone.setMinimumSize(QtCore.QSize(600, 200))
        self.fone.setMaximumSize(QtCore.QSize(600, 16777215))
        self.fone.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fone.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fone.setObjectName("fone")
        self.n_col_box = QtWidgets.QSpinBox(self.fone)
        self.n_col_box.setGeometry(QtCore.QRect(20, 50, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.n_col_box.setFont(font)
        self.n_col_box.setMinimum(1)
        self.n_col_box.setMaximum(7)
        self.n_col_box.setProperty("value", 6)
        self.n_col_box.setObjectName("n_col_box")
        self.col_lab = QtWidgets.QLabel(self.fone)
        self.col_lab.setGeometry(QtCore.QRect(20, 10, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.col_lab.setFont(font)
        self.col_lab.setObjectName("col_lab")
        self.save_but = QtWidgets.QPushButton(self.fone)
        self.save_but.setGeometry(QtCore.QRect(20, 130, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.save_but.setFont(font)
        self.save_but.setObjectName("save_but")
        self.gridLayout_2.addWidget(self.fone, 2, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 2, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)

        self.retranslateUi(AlbumsSettings)
        QtCore.QMetaObject.connectSlotsByName(AlbumsSettings)

    def retranslateUi(self, AlbumsSettings):
        _translate = QtCore.QCoreApplication.translate
        AlbumsSettings.setWindowTitle(_translate("AlbumsSettings", "Настройки вида альбомов"))
        self.title_lab.setText(_translate("AlbumsSettings", "Настройки ⚙"))
        self.to_themes_but.setText(_translate("AlbumsSettings", "Темы"))
        self.to_alb_view_but.setText(_translate("AlbumsSettings", "Вид альбомов"))
        self.to_user_but.setText(_translate("AlbumsSettings", "Пользовательские"))
        self.col_lab.setText(_translate("AlbumsSettings", "Введите количество колонок"))
        self.save_but.setText(_translate("AlbumsSettings", "Сохранить изменения"))


class Ui_ThemeSettings(object):
    def setupUi(self, ThemeSettings):
        ThemeSettings.setObjectName("ThemeSettings")
        ThemeSettings.resize(700, 500)
        ThemeSettings.setMinimumSize(QtCore.QSize(700, 500))
        ThemeSettings.setMaximumSize(QtCore.QSize(900, 700))
        self.gridLayout_2 = QtWidgets.QGridLayout(ThemeSettings)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 6, 1, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.to_themes_but = QtWidgets.QPushButton(ThemeSettings)
        self.to_themes_but.setMinimumSize(QtCore.QSize(0, 40))
        self.to_themes_but.setMaximumSize(QtCore.QSize(200, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.to_themes_but.setFont(font)
        self.to_themes_but.setObjectName("to_themes_but")
        self.gridLayout.addWidget(self.to_themes_but, 1, 0, 1, 1)
        self.to_alb_view_but = QtWidgets.QPushButton(ThemeSettings)
        self.to_alb_view_but.setMinimumSize(QtCore.QSize(0, 40))
        self.to_alb_view_but.setMaximumSize(QtCore.QSize(200, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.to_alb_view_but.setFont(font)
        self.to_alb_view_but.setObjectName("to_alb_view_but")
        self.gridLayout.addWidget(self.to_alb_view_but, 1, 1, 1, 1)
        self.to_user_but = QtWidgets.QPushButton(ThemeSettings)
        self.to_user_but.setMinimumSize(QtCore.QSize(0, 40))
        self.to_user_but.setMaximumSize(QtCore.QSize(200, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.to_user_but.setFont(font)
        self.to_user_but.setObjectName("to_user_but")
        self.gridLayout.addWidget(self.to_user_but, 1, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 1, 1, 1)
        self.title_lab = QtWidgets.QLabel(ThemeSettings)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.title_lab.setFont(font)
        self.title_lab.setObjectName("title_lab")
        self.gridLayout_2.addWidget(self.title_lab, 0, 1, 1, 1)
        self.fone = QtWidgets.QFrame(ThemeSettings)
        self.fone.setMinimumSize(QtCore.QSize(700, 400))
        self.fone.setMaximumSize(QtCore.QSize(700, 600))
        self.fone.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fone.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fone.setObjectName("fone")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.fone)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(40, 60, 161, 331))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.light_radio = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setUnderline(True)
        self.light_radio.setFont(font)
        self.light_radio.setChecked(True)
        self.light_radio.setObjectName("light_radio")
        self.buttonGroup = QtWidgets.QButtonGroup(ThemeSettings)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.light_radio)
        self.verticalLayout.addWidget(self.light_radio)
        self.dark_radio = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setUnderline(True)
        self.dark_radio.setFont(font)
        self.dark_radio.setChecked(False)
        self.dark_radio.setObjectName("dark_radio")
        self.buttonGroup.addButton(self.dark_radio)
        self.verticalLayout.addWidget(self.dark_radio)
        self.retro_radio = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setUnderline(True)
        self.retro_radio.setFont(font)
        self.retro_radio.setObjectName("retro_radio")
        self.buttonGroup.addButton(self.retro_radio)
        self.verticalLayout.addWidget(self.retro_radio)
        self.neon_radio = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setUnderline(True)
        self.neon_radio.setFont(font)
        self.neon_radio.setObjectName("neon_radio")
        self.buttonGroup.addButton(self.neon_radio)
        self.verticalLayout.addWidget(self.neon_radio)
        self.second_title_lab = QtWidgets.QLabel(self.fone)
        self.second_title_lab.setGeometry(QtCore.QRect(0, 10, 671, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.second_title_lab.setFont(font)
        self.second_title_lab.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.second_title_lab.setObjectName("second_title_lab")
        self.window_view = QtWidgets.QFrame(self.fone)
        self.window_view.setGeometry(QtCore.QRect(230, 60, 441, 251))
        self.window_view.setStyleSheet("")
        self.window_view.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.window_view.setFrameShadow(QtWidgets.QFrame.Raised)
        self.window_view.setObjectName("window_view")
        self.input_view = QtWidgets.QLineEdit(self.window_view)
        self.input_view.setGeometry(QtCore.QRect(10, 50, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.input_view.setFont(font)
        self.input_view.setObjectName("input_view")
        self.pushbut_view = QtWidgets.QPushButton(self.window_view)
        self.pushbut_view.setGeometry(QtCore.QRect(180, 50, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushbut_view.setFont(font)
        self.pushbut_view.setObjectName("pushbut_view")
        self.label_view = QtWidgets.QLabel(self.window_view)
        self.label_view.setGeometry(QtCore.QRect(10, 0, 201, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_view.setFont(font)
        self.label_view.setObjectName("label_view")
        self.dial_view = QtWidgets.QDial(self.window_view)
        self.dial_view.setGeometry(QtCore.QRect(280, 10, 101, 121))
        self.dial_view.setObjectName("dial_view")
        self.slider_view = QtWidgets.QSlider(self.window_view)
        self.slider_view.setGeometry(QtCore.QRect(390, 10, 41, 241))
        self.slider_view.setStyleSheet("")
        self.slider_view.setOrientation(QtCore.Qt.Vertical)
        self.slider_view.setObjectName("slider_view")
        self.fone_view = QtWidgets.QFrame(self.window_view)
        self.fone_view.setGeometry(QtCore.QRect(10, 100, 261, 141))
        self.fone_view.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fone_view.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fone_view.setObjectName("fone_view")
        self.radio_view = QtWidgets.QRadioButton(self.window_view)
        self.radio_view.setGeometry(QtCore.QRect(290, 130, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.radio_view.setFont(font)
        self.radio_view.setChecked(True)
        self.radio_view.setObjectName("radio_view")
        self.save_but = QtWidgets.QPushButton(self.fone)
        self.save_but.setGeometry(QtCore.QRect(490, 330, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.save_but.setFont(font)
        self.save_but.setObjectName("save_but")
        self.gridLayout_2.addWidget(self.fone, 5, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 5, 2, 1, 1)

        self.retranslateUi(ThemeSettings)
        QtCore.QMetaObject.connectSlotsByName(ThemeSettings)

    def retranslateUi(self, ThemeSettings):
        _translate = QtCore.QCoreApplication.translate
        ThemeSettings.setWindowTitle(_translate("ThemeSettings", "Настройки темы"))
        self.to_themes_but.setText(_translate("ThemeSettings", "Темы"))
        self.to_alb_view_but.setText(_translate("ThemeSettings", "Вид альбомов"))
        self.to_user_but.setText(_translate("ThemeSettings", "Пользовательские"))
        self.title_lab.setText(_translate("ThemeSettings", "Настройки ⚙"))
        self.light_radio.setText(_translate("ThemeSettings", "Светлая"))
        self.dark_radio.setText(_translate("ThemeSettings", "Тёмная"))
        self.retro_radio.setText(_translate("ThemeSettings", "Ретро"))
        self.neon_radio.setText(_translate("ThemeSettings", "Неоновая"))
        self.second_title_lab.setText(_translate("ThemeSettings", "      Темы"))
        self.input_view.setText(_translate("ThemeSettings", "Ввод"))
        self.pushbut_view.setText(_translate("ThemeSettings", "Кнопка"))
        self.label_view.setText(_translate("ThemeSettings", "Расцветка будет такой:"))
        self.radio_view.setText(_translate("ThemeSettings", "Кнопка"))
        self.save_but.setText(_translate("ThemeSettings", "Сохранить изменения"))


class Ui_UserSettings(object):
    def setupUi(self, UserSettings):
        UserSettings.setObjectName("UserSettings")
        UserSettings.resize(715, 570)
        UserSettings.setMinimumSize(QtCore.QSize(715, 570))
        UserSettings.setMaximumSize(QtCore.QSize(900, 700))
        self.gridLayout_4 = QtWidgets.QGridLayout(UserSettings)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.to_themes_but = QtWidgets.QPushButton(UserSettings)
        self.to_themes_but.setMinimumSize(QtCore.QSize(0, 40))
        self.to_themes_but.setMaximumSize(QtCore.QSize(200, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.to_themes_but.setFont(font)
        self.to_themes_but.setObjectName("to_themes_but")
        self.gridLayout.addWidget(self.to_themes_but, 1, 0, 1, 1)
        self.to_alb_view_but = QtWidgets.QPushButton(UserSettings)
        self.to_alb_view_but.setMinimumSize(QtCore.QSize(0, 40))
        self.to_alb_view_but.setMaximumSize(QtCore.QSize(200, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.to_alb_view_but.setFont(font)
        self.to_alb_view_but.setObjectName("to_alb_view_but")
        self.gridLayout.addWidget(self.to_alb_view_but, 1, 1, 1, 1)
        self.to_user_but = QtWidgets.QPushButton(UserSettings)
        self.to_user_but.setMinimumSize(QtCore.QSize(0, 40))
        self.to_user_but.setMaximumSize(QtCore.QSize(200, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.to_user_but.setFont(font)
        self.to_user_but.setObjectName("to_user_but")
        self.gridLayout.addWidget(self.to_user_but, 1, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 1)
        self.title_lab = QtWidgets.QLabel(UserSettings)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.title_lab.setFont(font)
        self.title_lab.setObjectName("title_lab")
        self.gridLayout_2.addWidget(self.title_lab, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 3, 0, 1, 1)
        self.frame = QtWidgets.QFrame(UserSettings)
        self.frame.setMinimumSize(QtCore.QSize(700, 450))
        self.frame.setMaximumSize(QtCore.QSize(700, 450))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.save_but = QtWidgets.QPushButton(self.frame)
        self.save_but.setGeometry(QtCore.QRect(500, 390, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.save_but.setFont(font)
        self.save_but.setObjectName("save_but")
        self.path_ed = QtWidgets.QLineEdit(self.frame)
        self.path_ed.setGeometry(QtCore.QRect(350, 30, 331, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.path_ed.setFont(font)
        self.path_ed.setText("")
        self.path_ed.setReadOnly(True)
        self.path_ed.setObjectName("path_ed")
        self.change_path_but = QtWidgets.QPushButton(self.frame)
        self.change_path_but.setGeometry(QtCore.QRect(500, 70, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.change_path_but.setFont(font)
        self.change_path_but.setObjectName("change_path_but")
        self.gridLayoutWidget = QtWidgets.QWidget(self.frame)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 316, 281))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.photo_lab = QtWidgets.QLabel(self.gridLayoutWidget)
        self.photo_lab.setMinimumSize(QtCore.QSize(200, 200))
        self.photo_lab.setMaximumSize(QtCore.QSize(200, 200))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.photo_lab.setFont(font)
        self.photo_lab.setAlignment(QtCore.Qt.AlignCenter)
        self.photo_lab.setObjectName("photo_lab")
        self.gridLayout_3.addWidget(self.photo_lab, 1, 1, 1, 1)
        self.nik_lab = QtWidgets.QLabel(self.gridLayoutWidget)
        self.nik_lab.setMinimumSize(QtCore.QSize(200, 60))
        self.nik_lab.setMaximumSize(QtCore.QSize(200, 60))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.nik_lab.setFont(font)
        self.nik_lab.setAlignment(QtCore.Qt.AlignCenter)
        self.nik_lab.setWordWrap(True)
        self.nik_lab.setObjectName("nik_lab")
        self.gridLayout_3.addWidget(self.nik_lab, 0, 1, 1, 1)
        self.change_photo_but = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.change_photo_but.setMinimumSize(QtCore.QSize(40, 50))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.change_photo_but.setFont(font)
        self.change_photo_but.setObjectName("change_photo_but")
        self.gridLayout_3.addWidget(self.change_photo_but, 1, 0, 1, 1)
        self.change_nik_but = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.change_nik_but.setMinimumSize(QtCore.QSize(40, 50))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.change_nik_but.setFont(font)
        self.change_nik_but.setObjectName("change_nik_but")
        self.gridLayout_3.addWidget(self.change_nik_but, 0, 0, 1, 1)
        self.change_password_but = QtWidgets.QPushButton(self.frame)
        self.change_password_but.setGeometry(QtCore.QRect(530, 310, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.change_password_but.setFont(font)
        self.change_password_but.setObjectName("change_password_but")
        self.log_pas_change_group = QtWidgets.QButtonGroup(UserSettings)
        self.log_pas_change_group.setObjectName("log_pas_change_group")
        self.log_pas_change_group.addButton(self.change_password_but)
        self.password_ed = QtWidgets.QLineEdit(self.frame)
        self.password_ed.setGeometry(QtCore.QRect(350, 270, 331, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.password_ed.setFont(font)
        self.password_ed.setReadOnly(True)
        self.password_ed.setObjectName("password_ed")
        self.password_lab = QtWidgets.QLabel(self.frame)
        self.password_lab.setGeometry(QtCore.QRect(350, 240, 331, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.password_lab.setFont(font)
        self.password_lab.setAlignment(QtCore.Qt.AlignCenter)
        self.password_lab.setObjectName("password_lab")
        self.path_lab = QtWidgets.QLabel(self.frame)
        self.path_lab.setGeometry(QtCore.QRect(350, 0, 331, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.path_lab.setFont(font)
        self.path_lab.setAlignment(QtCore.Qt.AlignCenter)
        self.path_lab.setObjectName("path_lab")
        self.login_lab = QtWidgets.QLabel(self.frame)
        self.login_lab.setGeometry(QtCore.QRect(350, 120, 331, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.login_lab.setFont(font)
        self.login_lab.setAlignment(QtCore.Qt.AlignCenter)
        self.login_lab.setObjectName("login_lab")
        self.login_ed = QtWidgets.QLineEdit(self.frame)
        self.login_ed.setGeometry(QtCore.QRect(350, 150, 331, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.login_ed.setFont(font)
        self.login_ed.setReadOnly(True)
        self.login_ed.setObjectName("login_ed")
        self.change_login_but = QtWidgets.QPushButton(self.frame)
        self.change_login_but.setGeometry(QtCore.QRect(530, 190, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.change_login_but.setFont(font)
        self.change_login_but.setObjectName("change_login_but")
        self.log_pas_change_group.addButton(self.change_login_but)
        self.gridLayout_2.addWidget(self.frame, 2, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 0, 1, 1, 1)

        self.retranslateUi(UserSettings)
        QtCore.QMetaObject.connectSlotsByName(UserSettings)

    def retranslateUi(self, UserSettings):
        _translate = QtCore.QCoreApplication.translate
        UserSettings.setWindowTitle(_translate("UserSettings", "Настройки пользователя"))
        self.to_themes_but.setText(_translate("UserSettings", "Темы"))
        self.to_alb_view_but.setText(_translate("UserSettings", "Вид альбомов"))
        self.to_user_but.setText(_translate("UserSettings", "Пользовательские"))
        self.title_lab.setText(_translate("UserSettings", "Настройки ⚙"))
        self.save_but.setText(_translate("UserSettings", "Сохранить изменения"))
        self.change_path_but.setText(_translate("UserSettings", "Выбрать другой путь"))
        self.photo_lab.setText(_translate("UserSettings", "Фото"))
        self.nik_lab.setText(_translate("UserSettings", "Ник"))
        self.change_photo_but.setText(_translate("UserSettings", "Сменить фото"))
        self.change_nik_but.setText(_translate("UserSettings", "Сменить ник"))
        self.change_password_but.setText(_translate("UserSettings", "Сменить пароль"))
        self.password_lab.setText(_translate("UserSettings", "Мой пароль:"))
        self.path_lab.setText(_translate("UserSettings", "Путь до моей базы данных:"))
        self.login_lab.setText(_translate("UserSettings", "Мой логин:"))
        self.change_login_but.setText(_translate("UserSettings", "Сменить логин"))


class Ui_Album(object):
    def setupUi(self, Album):
        Album.setObjectName("Album")
        Album.resize(721, 538)
        self.gridLayout_2 = QtWidgets.QGridLayout(Album)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cover_lab = QtWidgets.QLabel(Album)
        self.cover_lab.setMinimumSize(QtCore.QSize(200, 200))
        self.cover_lab.setMaximumSize(QtCore.QSize(200, 200))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cover_lab.setFont(font)
        self.cover_lab.setAlignment(QtCore.Qt.AlignCenter)
        self.cover_lab.setObjectName("cover_lab")
        self.verticalLayout.addWidget(self.cover_lab)
        self.alb_name_lab = QtWidgets.QLabel(Album)
        self.alb_name_lab.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.alb_name_lab.setFont(font)
        self.alb_name_lab.setAlignment(QtCore.Qt.AlignCenter)
        self.alb_name_lab.setWordWrap(True)
        self.alb_name_lab.setObjectName("alb_name_lab")
        self.verticalLayout.addWidget(self.alb_name_lab)
        self.download_but = QtWidgets.QPushButton(Album)
        self.download_but.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.download_but.setFont(font)
        self.download_but.setObjectName("download_but")
        self.verticalLayout.addWidget(self.download_but)
        self.delete_but = QtWidgets.QPushButton(Album)
        self.delete_but.setMinimumSize(QtCore.QSize(0, 40))
        self.delete_but.setMaximumSize(QtCore.QSize(1000000, 1000000))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.delete_but.setFont(font)
        self.delete_but.setObjectName("delete_but")
        self.verticalLayout.addWidget(self.delete_but)
        self.settings_but = QtWidgets.QPushButton(Album)
        self.settings_but.setMinimumSize(QtCore.QSize(0, 40))
        self.settings_but.setMaximumSize(QtCore.QSize(1000000, 1000000))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.settings_but.setFont(font)
        self.settings_but.setObjectName("settings_but")
        self.verticalLayout.addWidget(self.settings_but)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout_2.addLayout(self.verticalLayout, 1, 1, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.title_fon = QtWidgets.QFrame(Album)
        self.title_fon.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.title_fon.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_fon.setObjectName("title_fon")
        self.title_lab = QtWidgets.QLabel(self.title_fon)
        self.title_lab.setGeometry(QtCore.QRect(0, 0, 200, 45))
        self.title_lab.setMinimumSize(QtCore.QSize(200, 45))
        self.title_lab.setMaximumSize(QtCore.QSize(200, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.title_lab.setFont(font)
        self.title_lab.setAlignment(QtCore.Qt.AlignCenter)
        self.title_lab.setWordWrap(True)
        self.title_lab.setObjectName("title_lab")
        self.gridLayout.addWidget(self.title_fon, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.alb_setka = QtWidgets.QGridLayout()
        self.alb_setka.setObjectName("alb_setka")
        self.horizontalLayout.addLayout(self.alb_setka)
        spacerItem1 = QtWidgets.QSpacerItem(70, 48, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.search_ed = QtWidgets.QLineEdit(Album)
        self.search_ed.setMinimumSize(QtCore.QSize(225, 30))
        self.search_ed.setMaximumSize(QtCore.QSize(300, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.search_ed.setFont(font)
        self.search_ed.setObjectName("search_ed")
        self.horizontalLayout.addWidget(self.search_ed)
        self.search_but = QtWidgets.QPushButton(Album)
        self.search_but.setMinimumSize(QtCore.QSize(80, 25))
        self.search_but.setObjectName("search_but")
        self.horizontalLayout.addWidget(self.search_but)
        spacerItem2 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 3, 1, 1)
        self.scroll = QtWidgets.QScrollBar(Album)
        self.scroll.setMaximum(0)
        self.scroll.setOrientation(QtCore.Qt.Vertical)
        self.scroll.setObjectName("scroll")
        self.gridLayout_2.addWidget(self.scroll, 0, 0, 2, 1)

        self.retranslateUi(Album)
        QtCore.QMetaObject.connectSlotsByName(Album)

    def retranslateUi(self, Album):
        _translate = QtCore.QCoreApplication.translate
        Album.setWindowTitle(_translate("Album", "Альбом"))
        self.cover_lab.setText(_translate("Album", "Обложка"))
        self.alb_name_lab.setText(_translate("Album", "Название альбома"))
        self.download_but.setText(_translate("Album", "Загрузить картинку"))
        self.delete_but.setText(_translate("Album", "Удалить альбом"))
        self.settings_but.setText(_translate("Album", "Настройки ⚙"))
        self.title_lab.setText(_translate("Album", "Альбом"))
        self.search_ed.setText(_translate("Album", "Поиск"))
        self.search_but.setText(_translate("Album", "Поиск 🔍 "))


class Ui_AlbumSettings(object):
    def setupUi(self, AlbumSettings):
        AlbumSettings.setObjectName("AlbumSettings")
        AlbumSettings.resize(873, 472)
        AlbumSettings.setMinimumSize(QtCore.QSize(835, 415))
        AlbumSettings.setMaximumSize(QtCore.QSize(10000, 10000))
        self.gridLayout = QtWidgets.QGridLayout(AlbumSettings)
        self.gridLayout.setObjectName("gridLayout")
        self.title_lab = QtWidgets.QLabel(AlbumSettings)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.title_lab.setFont(font)
        self.title_lab.setObjectName("title_lab")
        self.gridLayout.addWidget(self.title_lab, 0, 0, 1, 1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setHorizontalSpacing(10)
        self.formLayout.setObjectName("formLayout")
        self.col_fone = QtWidgets.QFrame(AlbumSettings)
        self.col_fone.setMinimumSize(QtCore.QSize(300, 350))
        self.col_fone.setMaximumSize(QtCore.QSize(300, 350))
        self.col_fone.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.col_fone.setFrameShadow(QtWidgets.QFrame.Raised)
        self.col_fone.setObjectName("col_fone")
        self.n_col_box = QtWidgets.QSpinBox(self.col_fone)
        self.n_col_box.setGeometry(QtCore.QRect(20, 50, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.n_col_box.setFont(font)
        self.n_col_box.setMinimum(1)
        self.n_col_box.setMaximum(7)
        self.n_col_box.setProperty("value", 6)
        self.n_col_box.setObjectName("n_col_box")
        self.col_lab = QtWidgets.QLabel(self.col_fone)
        self.col_lab.setGeometry(QtCore.QRect(20, 10, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.col_lab.setFont(font)
        self.col_lab.setObjectName("col_lab")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.col_fone)
        self.alb_fone = QtWidgets.QFrame(AlbumSettings)
        self.alb_fone.setMinimumSize(QtCore.QSize(500, 350))
        self.alb_fone.setMaximumSize(QtCore.QSize(500, 350))
        self.alb_fone.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.alb_fone.setFrameShadow(QtWidgets.QFrame.Raised)
        self.alb_fone.setObjectName("alb_fone")
        self.alb_name_lab = QtWidgets.QLabel(self.alb_fone)
        self.alb_name_lab.setGeometry(QtCore.QRect(0, 0, 250, 40))
        self.alb_name_lab.setMinimumSize(QtCore.QSize(250, 40))
        self.alb_name_lab.setMaximumSize(QtCore.QSize(250, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.alb_name_lab.setFont(font)
        self.alb_name_lab.setAlignment(QtCore.Qt.AlignCenter)
        self.alb_name_lab.setWordWrap(True)
        self.alb_name_lab.setObjectName("alb_name_lab")
        self.cover_lab = QtWidgets.QLabel(self.alb_fone)
        self.cover_lab.setGeometry(QtCore.QRect(30, 70, 200, 200))
        self.cover_lab.setMinimumSize(QtCore.QSize(200, 200))
        self.cover_lab.setMaximumSize(QtCore.QSize(200, 200))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cover_lab.setFont(font)
        self.cover_lab.setAlignment(QtCore.Qt.AlignCenter)
        self.cover_lab.setObjectName("cover_lab")
        self.save_but = QtWidgets.QPushButton(self.alb_fone)
        self.save_but.setGeometry(QtCore.QRect(290, 280, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.save_but.setFont(font)
        self.save_but.setObjectName("save_but")
        self.change_cover_but = QtWidgets.QPushButton(self.alb_fone)
        self.change_cover_but.setGeometry(QtCore.QRect(300, 70, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.change_cover_but.setFont(font)
        self.change_cover_but.setObjectName("change_cover_but")
        self.change_alb_name_but = QtWidgets.QPushButton(self.alb_fone)
        self.change_alb_name_but.setGeometry(QtCore.QRect(300, 0, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.change_alb_name_but.setFont(font)
        self.change_alb_name_but.setObjectName("change_alb_name_but")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.alb_fone)
        self.gridLayout.addLayout(self.formLayout, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 2, 0, 1, 1)

        self.retranslateUi(AlbumSettings)
        QtCore.QMetaObject.connectSlotsByName(AlbumSettings)

    def retranslateUi(self, AlbumSettings):
        _translate = QtCore.QCoreApplication.translate
        AlbumSettings.setWindowTitle(_translate("AlbumSettings", "Настройки альбома"))
        self.title_lab.setText(_translate("AlbumSettings", "Настройки альбома ⚙"))
        self.col_lab.setText(_translate("AlbumSettings", "Количество колонок:"))
        self.alb_name_lab.setText(_translate("AlbumSettings", "Название альбома"))
        self.cover_lab.setText(_translate("AlbumSettings", "Обложка"))
        self.save_but.setText(_translate("AlbumSettings", "Сохранить изменения"))
        self.change_cover_but.setText(_translate("AlbumSettings", "Сменить обложку"))
        self.change_alb_name_but.setText(_translate("AlbumSettings", "Сменить название"))


class Ui_Image(object):
    def setupUi(self, Image):
        Image.setObjectName("Image")
        Image.resize(891, 494)
        self.gridLayout_2 = QtWidgets.QGridLayout(Image)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtWidgets.QLabel(Image)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(Image)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setHorizontalSpacing(40)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.name_lab = QtWidgets.QLabel(Image)
        self.name_lab.setMinimumSize(QtCore.QSize(300, 70))
        self.name_lab.setMaximumSize(QtCore.QSize(16777215, 70))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.name_lab.setFont(font)
        self.name_lab.setAlignment(QtCore.Qt.AlignCenter)
        self.name_lab.setObjectName("name_lab")
        self.horizontalLayout.addWidget(self.name_lab)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.change_name_but = QtWidgets.QPushButton(Image)
        self.change_name_but.setMinimumSize(QtCore.QSize(160, 40))
        self.change_name_but.setMaximumSize(QtCore.QSize(160, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.change_name_but.setFont(font)
        self.change_name_but.setObjectName("change_name_but")
        self.horizontalLayout.addWidget(self.change_name_but)
        self.edit_but = QtWidgets.QPushButton(Image)
        self.edit_but.setMinimumSize(QtCore.QSize(160, 40))
        self.edit_but.setMaximumSize(QtCore.QSize(160, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.edit_but.setFont(font)
        self.edit_but.setObjectName("edit_but")
        self.horizontalLayout.addWidget(self.edit_but)
        self.delete_but = QtWidgets.QPushButton(Image)
        self.delete_but.setMinimumSize(QtCore.QSize(160, 40))
        self.delete_but.setMaximumSize(QtCore.QSize(160, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.delete_but.setFont(font)
        self.delete_but.setObjectName("delete_but")
        self.horizontalLayout.addWidget(self.delete_but)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 2, 1, 1)
        self.image_area = QtWidgets.QScrollArea(Image)
        self.image_area.setWidgetResizable(True)
        self.image_area.setObjectName("image_area")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 849, 394))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.image_lab = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.image_lab.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.image_lab.setObjectName("image_lab")
        self.gridLayout_3.addWidget(self.image_lab, 0, 0, 1, 1)
        self.image_area.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.image_area, 1, 2, 1, 1)

        self.retranslateUi(Image)
        QtCore.QMetaObject.connectSlotsByName(Image)

    def retranslateUi(self, Image):
        _translate = QtCore.QCoreApplication.translate
        Image.setWindowTitle(_translate("Image", "Изображение"))
        self.name_lab.setText(_translate("Image", "Название картинки"))
        self.change_name_but.setText(_translate("Image", "Переименовать"))
        self.edit_but.setText(_translate("Image", "Редактировать"))
        self.delete_but.setText(_translate("Image", "Удалить"))
        self.image_lab.setText(_translate("Image", "TextLabel"))


class Ui_Editor(object):
    def setupUi(self, Editor):
        Editor.setObjectName("Editor")
        Editor.resize(750, 472)
        Editor.setMinimumSize(QtCore.QSize(750, 390))
        self.gridLayout_2 = QtWidgets.QGridLayout(Editor)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.title_lab = QtWidgets.QLabel(Editor)
        self.title_lab.setMinimumSize(QtCore.QSize(0, 30))
        self.title_lab.setMaximumSize(QtCore.QSize(170, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.title_lab.setFont(font)
        self.title_lab.setObjectName("title_lab")
        self.gridLayout_2.addWidget(self.title_lab, 0, 0, 4, 1)
        self.save_but = QtWidgets.QPushButton(Editor)
        self.save_but.setMinimumSize(QtCore.QSize(130, 0))
        self.save_but.setMaximumSize(QtCore.QSize(150, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.save_but.setFont(font)
        self.save_but.setObjectName("save_but")
        self.gridLayout_2.addWidget(self.save_but, 4, 4, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setHorizontalSpacing(6)
        self.gridLayout_3.setVerticalSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.blur_but = QtWidgets.QPushButton(Editor)
        self.blur_but.setMinimumSize(QtCore.QSize(100, 30))
        self.blur_but.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.blur_but.setFont(font)
        self.blur_but.setObjectName("blur_but")
        self.filters_gr = QtWidgets.QButtonGroup(Editor)
        self.filters_gr.setObjectName("filters_gr")
        self.filters_gr.addButton(self.blur_but)
        self.gridLayout_3.addWidget(self.blur_but, 2, 0, 1, 1)
        self.invert_but = QtWidgets.QPushButton(Editor)
        self.invert_but.setMinimumSize(QtCore.QSize(150, 30))
        self.invert_but.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.invert_but.setFont(font)
        self.invert_but.setObjectName("invert_but")
        self.filters_gr.addButton(self.invert_but)
        self.gridLayout_3.addWidget(self.invert_but, 1, 1, 1, 1)
        self.slice_but = QtWidgets.QPushButton(Editor)
        self.slice_but.setMinimumSize(QtCore.QSize(150, 30))
        self.slice_but.setMaximumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setUnderline(True)
        self.slice_but.setFont(font)
        self.slice_but.setObjectName("slice_but")
        self.gridLayout_3.addWidget(self.slice_but, 2, 2, 1, 1)
        self.change_size_but = QtWidgets.QPushButton(Editor)
        self.change_size_but.setMinimumSize(QtCore.QSize(150, 30))
        self.change_size_but.setMaximumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setUnderline(True)
        self.change_size_but.setFont(font)
        self.change_size_but.setObjectName("change_size_but")
        self.gridLayout_3.addWidget(self.change_size_but, 1, 2, 1, 1)
        self.w_b_but = QtWidgets.QPushButton(Editor)
        self.w_b_but.setMinimumSize(QtCore.QSize(100, 30))
        self.w_b_but.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.w_b_but.setFont(font)
        self.w_b_but.setObjectName("w_b_but")
        self.filters_gr.addButton(self.w_b_but)
        self.gridLayout_3.addWidget(self.w_b_but, 1, 0, 1, 1)
        self.cartooner_but = QtWidgets.QPushButton(Editor)
        self.cartooner_but.setMinimumSize(QtCore.QSize(150, 30))
        self.cartooner_but.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.cartooner_but.setFont(font)
        self.cartooner_but.setStyleSheet("background: rgb(249, 166, 2)")
        self.cartooner_but.setObjectName("cartooner_but")
        self.filters_gr.addButton(self.cartooner_but)
        self.gridLayout_3.addWidget(self.cartooner_but, 2, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_3, 1, 1, 5, 2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 4, 3, 1, 1)
        self.back_but = QtWidgets.QPushButton(Editor)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.back_but.setFont(font)
        self.back_but.setObjectName("back_but")
        self.filters_gr.addButton(self.back_but)
        self.gridLayout_2.addWidget(self.back_but, 0, 1, 1, 2)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.b_lab = QtWidgets.QLabel(Editor)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setUnderline(True)
        self.b_lab.setFont(font)
        self.b_lab.setAlignment(QtCore.Qt.AlignCenter)
        self.b_lab.setObjectName("b_lab")
        self.gridLayout_4.addWidget(self.b_lab, 0, 2, 1, 1)
        self.r_lab = QtWidgets.QLabel(Editor)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setUnderline(True)
        self.r_lab.setFont(font)
        self.r_lab.setAlignment(QtCore.Qt.AlignCenter)
        self.r_lab.setObjectName("r_lab")
        self.gridLayout_4.addWidget(self.r_lab, 0, 0, 1, 1)
        self.g_lab = QtWidgets.QLabel(Editor)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setUnderline(True)
        self.g_lab.setFont(font)
        self.g_lab.setAlignment(QtCore.Qt.AlignCenter)
        self.g_lab.setObjectName("g_lab")
        self.gridLayout_4.addWidget(self.g_lab, 0, 1, 1, 1)
        self.red_sl = QtWidgets.QSlider(Editor)
        self.red_sl.setMinimumSize(QtCore.QSize(30, 0))
        self.red_sl.setMaximum(255)
        self.red_sl.setOrientation(QtCore.Qt.Vertical)
        self.red_sl.setObjectName("red_sl")
        self.gridLayout_4.addWidget(self.red_sl, 1, 0, 1, 1)
        self.green_sl = QtWidgets.QSlider(Editor)
        self.green_sl.setMinimumSize(QtCore.QSize(30, 0))
        self.green_sl.setMaximum(255)
        self.green_sl.setOrientation(QtCore.Qt.Vertical)
        self.green_sl.setObjectName("green_sl")
        self.gridLayout_4.addWidget(self.green_sl, 1, 1, 1, 1)
        self.apply_components = QtWidgets.QPushButton(Editor)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.apply_components.setFont(font)
        self.apply_components.setObjectName("apply_components")
        self.gridLayout_4.addWidget(self.apply_components, 2, 0, 1, 3)
        self.blue_sl = QtWidgets.QSlider(Editor)
        self.blue_sl.setMinimumSize(QtCore.QSize(30, 0))
        self.blue_sl.setStyleSheet("")
        self.blue_sl.setMaximum(255)
        self.blue_sl.setOrientation(QtCore.Qt.Vertical)
        self.blue_sl.setObjectName("blue_sl")
        self.gridLayout_4.addWidget(self.blue_sl, 1, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_4, 6, 0, 1, 1)
        self.apply_contrast = QtWidgets.QPushButton(Editor)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.apply_contrast.setFont(font)
        self.apply_contrast.setObjectName("apply_contrast")
        self.gridLayout_2.addWidget(self.apply_contrast, 5, 0, 1, 1)
        self.contrast_dial = QtWidgets.QDial(Editor)
        self.contrast_dial.setMinimumSize(QtCore.QSize(30, 100))
        self.contrast_dial.setMaximumSize(QtCore.QSize(170, 100))
        self.contrast_dial.setMinimum(10)
        self.contrast_dial.setMaximum(245)
        self.contrast_dial.setObjectName("contrast_dial")
        self.gridLayout_2.addWidget(self.contrast_dial, 4, 0, 1, 1)
        self.image_area = QtWidgets.QScrollArea(Editor)
        self.image_area.setWidgetResizable(True)
        self.image_area.setObjectName("image_area")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 573, 276))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.image_lab = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.image_lab.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.image_lab.setObjectName("image_lab")
        self.gridLayout_5.addWidget(self.image_lab, 0, 0, 1, 1)
        self.image_area.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.image_area, 6, 1, 1, 4)

        self.retranslateUi(Editor)
        QtCore.QMetaObject.connectSlotsByName(Editor)

    def retranslateUi(self, Editor):
        _translate = QtCore.QCoreApplication.translate
        Editor.setWindowTitle(_translate("Editor", "ИЗОбработчик"))
        self.title_lab.setText(_translate("Editor", "ИЗОбработчик"))
        self.save_but.setText(_translate("Editor", "Сохранить как"))
        self.blur_but.setText(_translate("Editor", "Размытие"))
        self.invert_but.setText(_translate("Editor", "Инвертирование"))
        self.slice_but.setText(_translate("Editor", "Обрезка"))
        self.change_size_but.setText(_translate("Editor", "Изменение размера"))
        self.w_b_but.setText(_translate("Editor", "Чёрно-белое"))
        self.cartooner_but.setText(_translate("Editor", "Обмультяшиватель"))
        self.back_but.setText(_translate("Editor", "Вернуться к изначальному виду"))
        self.b_lab.setText(_translate("Editor", "С"))
        self.r_lab.setText(_translate("Editor", "К"))
        self.g_lab.setText(_translate("Editor", "З"))
        self.apply_components.setText(_translate("Editor", "Применить"))
        self.apply_contrast.setText(_translate("Editor", "Применить контраст"))
        self.image_lab.setText(_translate("Editor", "TextLabel"))


class Ui_ResizeDialog(object):
    def setupUi(self, ResizeDialog):
        ResizeDialog.setObjectName("ResizeDialog")
        ResizeDialog.resize(323, 190)
        self.gridLayout_2 = QtWidgets.QGridLayout(ResizeDialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.y_lab = QtWidgets.QLabel(ResizeDialog)
        self.y_lab.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.y_lab.setFont(font)
        self.y_lab.setAlignment(QtCore.Qt.AlignCenter)
        self.y_lab.setObjectName("y_lab")
        self.gridLayout.addWidget(self.y_lab, 2, 0, 1, 1)
        self.size_lab = QtWidgets.QLabel(ResizeDialog)
        self.size_lab.setMinimumSize(QtCore.QSize(0, 40))
        self.size_lab.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.size_lab.setFont(font)
        self.size_lab.setAlignment(QtCore.Qt.AlignCenter)
        self.size_lab.setObjectName("size_lab")
        self.gridLayout.addWidget(self.size_lab, 0, 0, 1, 1)
        self.x_col_box = QtWidgets.QSpinBox(ResizeDialog)
        self.x_col_box.setMinimumSize(QtCore.QSize(170, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.x_col_box.setFont(font)
        self.x_col_box.setMinimum(15)
        self.x_col_box.setMaximum(2000)
        self.x_col_box.setObjectName("x_col_box")
        self.gridLayout.addWidget(self.x_col_box, 1, 1, 1, 1)
        self.y_col_box = QtWidgets.QSpinBox(ResizeDialog)
        self.y_col_box.setMinimumSize(QtCore.QSize(170, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.y_col_box.setFont(font)
        self.y_col_box.setMinimum(15)
        self.y_col_box.setMaximum(2000)
        self.y_col_box.setObjectName("y_col_box")
        self.gridLayout.addWidget(self.y_col_box, 2, 1, 1, 1)
        self.x_lab = QtWidgets.QLabel(ResizeDialog)
        self.x_lab.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.x_lab.setFont(font)
        self.x_lab.setAlignment(QtCore.Qt.AlignCenter)
        self.x_lab.setObjectName("x_lab")
        self.gridLayout.addWidget(self.x_lab, 1, 0, 1, 1)
        self.cur_size_lab = QtWidgets.QLabel(ResizeDialog)
        self.cur_size_lab.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cur_size_lab.setFont(font)
        self.cur_size_lab.setAlignment(QtCore.Qt.AlignCenter)
        self.cur_size_lab.setObjectName("cur_size_lab")
        self.gridLayout.addWidget(self.cur_size_lab, 0, 1, 1, 1)
        self.apply_but = QtWidgets.QPushButton(ResizeDialog)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.apply_but.setFont(font)
        self.apply_but.setObjectName("apply_but")
        self.gridLayout.addWidget(self.apply_but, 3, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 1, 0, 1, 1)

        self.retranslateUi(ResizeDialog)
        QtCore.QMetaObject.connectSlotsByName(ResizeDialog)

    def retranslateUi(self, ResizeDialog):
        _translate = QtCore.QCoreApplication.translate
        ResizeDialog.setWindowTitle(_translate("ResizeDialog", "Изменение размера"))
        self.y_lab.setText(_translate("ResizeDialog", "Сменить высоту:"))
        self.size_lab.setText(_translate("ResizeDialog", "Текущий размер:"))
        self.x_lab.setText(_translate("ResizeDialog", "Сменить ширину:"))
        self.cur_size_lab.setText(_translate("ResizeDialog", "100 Х 100"))
        self.apply_but.setText(_translate("ResizeDialog", "Применить"))


class Ui_SliceDialog(object):
    def setupUi(self, SliceDialog):
        SliceDialog.setObjectName("SliceDialog")
        SliceDialog.resize(392, 158)
        self.gridLayout_2 = QtWidgets.QGridLayout(SliceDialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 2, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.x2_box = QtWidgets.QSpinBox(SliceDialog)
        self.x2_box.setMinimumSize(QtCore.QSize(70, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.x2_box.setFont(font)
        self.x2_box.setObjectName("x2_box")
        self.gridLayout.addWidget(self.x2_box, 2, 2, 1, 1)
        self.begin_coords_lab = QtWidgets.QLabel(SliceDialog)
        self.begin_coords_lab.setMinimumSize(QtCore.QSize(180, 0))
        self.begin_coords_lab.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.begin_coords_lab.setFont(font)
        self.begin_coords_lab.setAlignment(QtCore.Qt.AlignCenter)
        self.begin_coords_lab.setObjectName("begin_coords_lab")
        self.gridLayout.addWidget(self.begin_coords_lab, 1, 0, 1, 2)
        self.y2_box = QtWidgets.QSpinBox(SliceDialog)
        self.y2_box.setMinimumSize(QtCore.QSize(70, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.y2_box.setFont(font)
        self.y2_box.setObjectName("y2_box")
        self.gridLayout.addWidget(self.y2_box, 2, 3, 1, 1)
        self.end_coords_lab = QtWidgets.QLabel(SliceDialog)
        self.end_coords_lab.setMinimumSize(QtCore.QSize(180, 0))
        self.end_coords_lab.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.end_coords_lab.setFont(font)
        self.end_coords_lab.setAlignment(QtCore.Qt.AlignCenter)
        self.end_coords_lab.setObjectName("end_coords_lab")
        self.gridLayout.addWidget(self.end_coords_lab, 1, 2, 1, 2)
        self.cur_size_lab = QtWidgets.QLabel(SliceDialog)
        self.cur_size_lab.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cur_size_lab.setFont(font)
        self.cur_size_lab.setAlignment(QtCore.Qt.AlignCenter)
        self.cur_size_lab.setObjectName("cur_size_lab")
        self.gridLayout.addWidget(self.cur_size_lab, 0, 2, 1, 2)
        self.size_lab = QtWidgets.QLabel(SliceDialog)
        self.size_lab.setMinimumSize(QtCore.QSize(0, 40))
        self.size_lab.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.size_lab.setFont(font)
        self.size_lab.setAlignment(QtCore.Qt.AlignCenter)
        self.size_lab.setObjectName("size_lab")
        self.gridLayout.addWidget(self.size_lab, 0, 0, 1, 2)
        self.x1_box = QtWidgets.QSpinBox(SliceDialog)
        self.x1_box.setMinimumSize(QtCore.QSize(70, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.x1_box.setFont(font)
        self.x1_box.setObjectName("x1_box")
        self.gridLayout.addWidget(self.x1_box, 2, 0, 1, 1)
        self.y1_box = QtWidgets.QSpinBox(SliceDialog)
        self.y1_box.setMinimumSize(QtCore.QSize(70, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.y1_box.setFont(font)
        self.y1_box.setObjectName("y1_box")
        self.gridLayout.addWidget(self.y1_box, 2, 1, 1, 1)
        self.apply_but = QtWidgets.QPushButton(SliceDialog)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.apply_but.setFont(font)
        self.apply_but.setObjectName("apply_but")
        self.gridLayout.addWidget(self.apply_but, 3, 2, 1, 2)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(SliceDialog)
        QtCore.QMetaObject.connectSlotsByName(SliceDialog)

    def retranslateUi(self, SliceDialog):
        _translate = QtCore.QCoreApplication.translate
        SliceDialog.setWindowTitle(_translate("SliceDialog", "Обрезка"))
        self.begin_coords_lab.setText(_translate("SliceDialog", "Начальные координаты:"))
        self.end_coords_lab.setText(_translate("SliceDialog", "Конечные координаты:"))
        self.cur_size_lab.setText(_translate("SliceDialog", "100 Х 100"))
        self.size_lab.setText(_translate("SliceDialog", "Текущий размер:"))
        self.apply_but.setText(_translate("SliceDialog", "Применить"))
